# Doctrine mapping, entity configuration xml Driver
services:
  sexy_field.xml_driver:
    class: Doctrine\ORM\Mapping\Driver\XmlDriver
    arguments:
      -
        - "%kernel.root_dir%/../vendor/tardigrades/sexy-field/src/config/xml"
      - ".dcm.xml"
