# Doctrine mapping, entity configuration xml Driver
services:
  sexy_field.xml_driver:
    class: Doctrine\ORM\Mapping\Driver\XmlDriver
    arguments:
      -
        - "%kernel.root_dir%/../vendor/tardigrades/sexy-field/src/config/xml"
      - ".dcm.xml"

# This is the configuration that assumes you use the sexy-field-doctrine package
  section_field.generator:
    class: Tardigrades\SectionField\Generator\Generators
    arguments:
      -
        - '@section_field.generator.entity_generator'
        - '@section_field.generator.doctrine_config_generator'

  section_field.create.section:
    class: Tardigrades\SectionField\Service\CreateSection
    arguments:
      -
        - '@section_field.doctrine.create.section'

  section_field.read.section:
    class: Tardigrades\SectionField\Service\ReadSection
    arguments:
      -
        - '@section_field.doctrine.read.section'
      - '@section_field.manager.doctrine.section_manager'

  section_field.delete.section:
    class: Tardigrades\SectionField\Service\DeleteSection
    arguments:
      -
        - '@section_field.doctrine.delete.section'
